on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: build plugin
        run: |
          gradle buildDependents
          gradle build
      - name: upload artfacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/*
  gen-release-note:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: refs/tags/v*
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install auto-changelog
        run: npm install -g auto-changelog

      - name: generate changelog
        run: >-
          auto-changelog -t keepachangelog
          --commit-limit 50 --backfill-limit 50
          --ignore-commit-pattern '[Bb]ump version|[Uu]pdate changelog|[Mm]erge pull request'      

      - name: get release notes
        uses: olofvndrhr/releasenote-gen@v1
        with:
          version: latest # default
          changelog: CHANGELOG.md # default
          releasenotes: RELEASENOTES.md # default
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ build, gen-release-note ]
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'plugin'
          body: ${{  steps.gen-release-note.outputs.releaseNotes  }}